### ISSUE TITLE
Can't connect.

### ISSUE THREAD

**Issue by koma25** [bderleta/vevor-ble-bridge#11]
Hello. Could you help? The heater is from another manufacturer, but it seems to me that this is an exact copy. Here is the log:

Docker:
2024-11-03T12:35:06.463714576Z 2024-11-03 12:35:06 +0000 [INFO] Connecting to MQTT broker 172.20.0.1:1883

2024-11-03T12:35:06.476836574Z Traceback (most recent call last):

2024-11-03T12:35:06.476911369Z   File "//./main.py", line 330, in <module>

2024-11-03T12:35:06.477265269Z     vdh = vevor.DieselHeater(ble_mac_address, ble_passkey)

2024-11-03T12:35:06.477395229Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-11-03T12:35:06.477443061Z   File "/vevor.py", line 136, in __init__

2024-11-03T12:35:06.477710871Z     self.peripheral = Peripheral(mac_address, "public")

2024-11-03T12:35:06.477788591Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-11-03T12:35:06.477800035Z   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 391, in __init__

2024-11-03T12:35:06.478096825Z     self._connect(deviceAddr, addrType, iface)

2024-11-03T12:35:06.478172472Z   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 439, in _connect

2024-11-03T12:35:06.478486669Z     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)

2024-11-03T12:35:06.478569186Z bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 98:89:17:04:41:5E, addr type: public

gatttool:

admin@docker:~/vevor-ble-bridge $ gatttool -I -b 98:89:17:04:41:5E
[98:89:17:04:41:5E][LE]> connect
Attempting to connect to 98:89:17:04:41:5E
Connection successful
[98:89:17:04:41:5E][LE]> primary
attr handle: 0x0001, end grp handle: 0x0009 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle: 0x000a, end grp handle: 0x000a uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle: 0x000b, end grp handle: 0x000e uuid: 0000ffe0-0000-1000-8000-00805f9b34fb
attr handle: 0x000f, end grp handle: 0x0012 uuid: 0000180f-0000-1000-8000-00805f9b34fb

**Comment by corrosive4354** [comment]
If the bluepy library continues to fail when connecting, you can consider using other libraries (such as pygatt or bleak) for BLE connection to see if that solves the problem.

In addition, seeing that you are using docker, I would like to recommend [Servbay](https://servbay.com) to you, which is more professional and easy to use than docker on Mac

**Comment by bderleta** [comment]
Hard to say, it may be privilege issue (bluepy can't properly access hci device), may be a library (bluepy) problem. It fails in the very first step of connection, there's nothing I can tweak on my side. 
How many BT adapters do you have? Please provide an output from `hciconfig -a`
