### ISSUE TITLE
Stops working after few hours

### ISSUE THREAD

**Issue by donnib** [bderleta/vevor-ble-bridge#13]
Hi,
My installation get stuck after few hours, running ethernet on rPi and the rPi is rather close to the heater. In the docker logs for the container i can see no error but no status is pushed to mqtt anymore. Any ideas what's causing this ?

This is how it looks in the log when it's stuck :

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/a07381ab-5a2c-4fed-aed6-a8af08989565">

Nothing worrying what i can see.

I tried to restart the docker container and i get :

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/d27d26c7-827f-4a01-b7ae-a6ccab0f5f5a">

So it could look like it can't reconnect to the heater so i tried to see if i can connect from the AirHeater app and i can so something on rPi part is not working as i should.

**Comment by nowcodingaway** [comment]
Mine connects for a short while, and then just randomly disconnects. Reporting the entire pi5 brings it back to life for a bit then the same thing again.

While I don't have a solution for you, I thought I would add my logs here in case they start to present more of a picture.

You can see here it runs for a few lines and then a big error
```

vevor-ble-bridge_1  | 2024-11-22 15:28:11 +0000 [INFO] Connecting to MQTT broker redacted@192.168.5.204:1883
vevor-ble-bridge_1  | 2024-11-22 15:28:12 +0000 [INFO] Connected to MQTT broker
vevor-ble-bridge_1  | 2024-11-22 15:28:12 +0000 [DEBUG] {'running_state': 1, 'error': 0, 'error_msg': 'No fault', 'running_step': 3, 'running_step_msg': 'Running', 'altitude': 0, 'running_mode': 1, 'set_level': 10, 'set_temperature': None, 'supply_voltage': 12.7, 'case_temperature': 207, 'cab_temperature': 15, 'md': 1}
vevor-ble-bridge_1  | 2024-11-22 15:28:15 +0000 [DEBUG] {'running_state': 1, 'error': 0, 'error_msg': 'No fault', 'running_step': 3, 'running_step_msg': 'Running', 'altitude': 0, 'running_mode': 1, 'set_level': 10, 'set_temperature': None, 'supply_voltage': 12.7, 'case_temperature': 208, 'cab_temperature': 15, 'md': 1}
vevor-ble-bridge_1  | Traceback (most recent call last):
vevor-ble-bridge_1  |   File "//./main.py", line 334, in <module>
vevor-ble-bridge_1  |     result = vdh.get_status()
vevor-ble-bridge_1  |              ^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/vevor.py", line 170, in get_status
vevor-ble-bridge_1  |     return self._send_command(1, 0, 85)
vevor-ble-bridge_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/vevor.py", line 161, in _send_command
vevor-ble-bridge_1  |     response = self.characteristic.write(
vevor-ble-bridge_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 200, in write
vevor-ble-bridge_1  |     return self.peripheral.writeCharacteristic(self.valHandle, val, withResponse)
vevor-ble-bridge_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
vevor-ble-bridge_1  |     return self._getResp('wr')
vevor-ble-bridge_1  |            ^^^^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 407, in _getResp
vevor-ble-bridge_1  |     resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
vevor-ble-bridge_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 362, in _waitResp
vevor-ble-bridge_1  |     raise BTLEDisconnectError("Device disconnected", resp)
vevor-ble-bridge_1  | bluepy.btle.BTLEDisconnectError: Device disconnected
vevor-ble-bridge_1  | 2024-11-22 15:28:23 +0000 [INFO] Connecting to MQTT broker redacted@192.168.5.204:1883
vevor-ble-bridge_1  | Traceback (most recent call last):
vevor-ble-bridge_1  |   File "//./main.py", line 330, in <module>
vevor-ble-bridge_1  |     vdh = vevor.DieselHeater(ble_mac_address, ble_passkey)
vevor-ble-bridge_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/vevor.py", line 136, in __init__
vevor-ble-bridge_1  |     self.peripheral = Peripheral(mac_address, "public")
vevor-ble-bridge_1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vevor-ble-bridge_1  |   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 391, in __init__
vevor-ble-bridge_1  |     self._connect(deviceAddr, addrType, iface)
vevor-ble-bridge_1  |   File "/usr/local/lib/python3.11/site-packages/bluepy/btle.py", line 439, in _connect
vevor-ble-bridge_1  |     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
vevor-ble-bridge_1  | bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral C7:7C:13:23:01:34, addr type: public
vevor-ble-bridge_1  | 2024-11-22 15:28:37 +0000 [INFO] Connecting to MQTT broker redacted@192.168.5.204:1883
vevor-ble-bridge_1  | Traceback (most recent call last):
vevor-ble-bridge_1  |   File "//./main.py", line 330, in <module>

```

**Comment by nowcodingaway** [comment]
As an aside, I know that another project has had much better success using the 'bleak' bluetooth library as it seems to be more dependable. Not sure if that might be something that could get factored into here.

**Comment by bderleta** [comment]
Yeah, I do get lot of complaints about BT stability. All the heavy lifting is on the bluepy library, so there's no other solution than rewriting to something potentially more stable. During my tests I had an impression that sometimes it's the device which is not responding, but it may be the lib issue really.
