### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by sedlacekdavid** [bderleta/vevor-ble-bridge#15]
Hello, I'm running Homeassistant OS and executing commands in unprotected mode Terminal addon. 

Any ideas what can be wrong? MQTT is running on 192.168.9.123 (accessible even from outside the system):

```
2024-12-15 17:10:37 +0000 [INFO] Connecting to MQTT broker "mqtt"@"192.168.9.123":1883
Traceback (most recent call last):
  File "//./main.py", line 329, in <module>
    client = init_client()
             ^^^^^^^^^^^^^
  File "//./main.py", line 72, in init_client
    client.connect(mqtt_host, port=mqtt_port)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 839, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
```

```
➜  vevor-ble-bridge git:(master) cat .env
# MAC address of heater controller
BLE_MAC_ADDRESS="aa:bb:cc:dd:ee:ff"
# Adjust accordingly if needed
BLE_PASSKEY=1234
# Those are to be shown in HomeAssistant
DEVICE_NAME="Diesel Heater"
DEVICE_MANUFACTURER="Vevor"
DEVICE_MODEL="XMZ-D1"
# MQTT broker host
MQTT_HOST="192.168.9.123"
# Leave empty if broker auth is disabled, otherwise adjust
MQTT_USERNAME="mqtt"
MQTT_PASSWORD="mqttmqtt"
MQTT_PREFIX="home"
```

**Comment by sedlacekdavid** [comment]
Hi, FYI I was running Pi 3 with only 1 GB RAM -> apparently services were crashing on the background. Now with Pi 5 4 GB RAM it starts alright.
